version: '3.8'

services:
  # UK Open Banking - Account Information API
  uk-account-information:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE=uk-account-information
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SERVICE=uk-account-information
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # UK Open Banking - Payment Initiation API (uncomment when implemented)
  # uk-payment-initiation:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - SERVICE=uk-payment-initiation
  #   ports:
  #     - "3002:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3001
  #     - SERVICE=uk-payment-initiation
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s

  # Brazil Open Banking - Account Information API (uncomment when implemented)
  # brazil-account-information:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - SERVICE=brazil-account-information
  #   ports:
  #     - "3003:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3001
  #     - SERVICE=brazil-account-information
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s

  # Uncomment the following section if you want to add a UI for API documentation
  # Note: You would need to implement an OpenAPI specification endpoint first
  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - API_URL=http://localhost:3001/  # Currently no OpenAPI spec endpoint exists
  #   depends_on:
  #     - uk-account-information
