version: '3'

services:
  tyk-grpc-plugin-fapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    restart: unless-stopped
    networks:
      - tyk-network

networks:
  tyk-network:
    external: true
