services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # OTLP HTTP ingest
      - "4317:4317"    # OTLP gRPC ingest (used by OpenTelemetry SDKs)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - tyk-network
